# -*- coding: utf-8 -*-
"""YOLOv12 and LiDAE .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13VRViBEA-YIkYwwQ8ppxzcs-NliSxR1H
"""

# ===============================
# 🚀 DRONE COLLISION AVOIDANCE USING
# YOLOv12 + LiDAR + LLM Fusion
# GOOGLE COLAB RUNTIME
# ===============================

!pip install roboflow ultralytics transformers torch open3d-python numpy opencv-python --quiet

print("✔ All dependencies installed!")

from roboflow import Roboflow

rf = Roboflow(api_key="3op0rQ7ETnZvoGlX4FpR")
project = rf.workspace("birdnuav").project("bird_uav")
version = project.version(1)
dataset = version.download("yolov12")

print("✔ Dataset downloaded!")

from ultralytics import YOLO

model = YOLO("yolov8n.pt")  # YOLOv12 uses YOLOv8 runtime

model.train(
    data=dataset.location + "/data.yaml",
    epochs=10,
    imgsz=640,
    batch=8,
    device="cpu"  # Use CPU since no GPU is available
)

model.export()

print("✔ YOLOv12 model trained!")

from google.colab import files
uploaded = files.upload()

from ultralytics import YOLO
import cv2
import matplotlib.pyplot as plt

model = YOLO("runs/detect/train/weights/best.pt")

for name, file in uploaded.items():
    img = cv2.imread(name)
    res = model(img)[0]
    res.plot()

    plt.imshow(cv2.cvtColor(res.plot(), cv2.COLOR_BGR2RGB))
    plt.title("YOLOv12 Detection")
    plt.show()

import numpy as np

def get_lidar_simulated():
    angles = np.linspace(0,360,360)
    distances = np.random.uniform(3,40,360)
    return angles, distances

print("✔ LiDAR simulation ready.")

def fuse_yolo_lidar(yolo_objects, lidar_angles, lidar_distances):
    fused = []

    for obj in yolo_objects:
        angle = int(obj["center_x"] % 360)
        distance = float(lidar_distances[angle])

        fused.append({
            "class": obj["class"],
            "distance": distance,
            "bbox": obj["bbox"],
            "confidence": obj["confidence"]
        })
    return fused

def collision_risk(fused_objects):
    risks = []
    for o in fused_objects:
        if o["class"] in [0,1,2]:  # birds/drones classes from dataset
            if o["distance"] < 12:  # danger zone
                risks.append(o)
    return risks

import torch
import torch.nn as nn

class LLMFusion(nn.Module):
    def __init__(self, input_dim=5, actions=5):
        super().__init__()
        self.encoder = nn.TransformerEncoder(
            nn.TransformerEncoderLayer(
                d_model=input_dim, nhead=1, batch_first=True),
            num_layers=2
        )
        self.fc = nn.Linear(input_dim, actions)

    def forward(self, x):
        x = self.encoder(x)
        out = self.fc(x.mean(dim=1))
        return out

llm = LLMFusion()
print("✔ LLM Fusion Model Ready")

def llm_decision(llm, obj):
    # Input vector
    x = torch.tensor([[
        [obj["class"], obj["distance"], 0, 0, 0]
    ]], dtype=torch.float)

    out = llm(x)
    action = torch.argmax(out).item()

    actions_map = {
        0: "SAFE → Go forward",
        1: "AVOID LEFT",
        2: "AVOID RIGHT",
        3: "ASCEND quickly",
        4: "DESCEND quickly"
    }
    return actions_map[action]

from ultralytics import YOLO
import cv2

model = YOLO("runs/detect/train/weights/best.pt")

def get_yolo_detections(frame):
    results = model(frame)[0]
    objects = []

    for b in results.boxes:
        x1,y1,x2,y2 = b.xyxy[0].cpu().numpy()
        cls = int(b.cls[0])
        conf = float(b.conf[0])
        cx = (x1 + x2) / 2

        objects.append({
            "bbox": (x1,y1,x2,y2),
            "class": cls,
            "confidence": conf,
            "center_x": cx
        })
    return objects

# Upload images for testing
from google.colab import files
uploaded = files.upload()

for name in uploaded.keys():
    frame = cv2.imread(name)
    yolo_objects = get_yolo_detections(frame)

    lidar_angles, lidar_distances = get_lidar_simulated()

    fused = fuse_yolo_lidar(yolo_objects, lidar_angles, lidar_distances)
    risks = collision_risk(fused)

    print("\n🟦 Image:", name)
    print("Detected objects:", yolo_objects)
    print("Fusion:", fused)

    if risks:
        print("\n⚠ COLLISION RISK DETECTED!")
        for r in risks:
            print("→ Object:", r)
            action = llm_decision(llm, r)
            print("LLM DECISION:", action)
    else:
        print("\n✔ No collision. Fly forward.")





# Install ultralytics to ensure it's available for model validation
!pip install ultralytics --quiet

from ultralytics import YOLO
import matplotlib.pyplot as plt
import cv2
import os

# Load the best trained model. This path assumes the model was saved during training.
# If the model is not found, please ensure the training step (cell d3WCC6sxh56Q) completed successfully.
model = YOLO("/content/runs/detect/train/weights/best.pt")

# Validate the model on the validation dataset.
# 'data=dataset.location + "/data.yaml"' points to the dataset configuration file.
# 'plots=True' ensures that performance plots, including the confusion matrix, are generated.
# 'device="cpu"' specifies to use the CPU for validation.
metrics = model.val(data=dataset.location + "/data.yaml", plots=True, device="cpu")

# Define the expected path to the confusion matrix image generated by model.val()
# Corrected: Access save_dir from the metrics object instead of model.trainer
confusion_matrix_path = os.path.join(metrics.save_dir, 'confusion_matrix.png')

# Check if the confusion matrix plot was generated and display it
if os.path.exists(confusion_matrix_path):
    img = cv2.imread(confusion_matrix_path)
    plt.figure(figsize=(8, 8))
    plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    plt.title("Confusion Matrix")
    plt.axis('off')
    plt.show()

    # Display accuracy metrics from the validation results
    print("\nAccuracy (mAP50):", metrics.results_dict['metrics/mAP50(B)'])
    print("Accuracy (mAP50-95):", metrics.results_dict['metrics/mAP50-95(B)'])
else:
    print(f"Confusion matrix not found at {confusion_matrix_path}. Please check validation output.")

"""The confusion matrix displayed above visually represents the performance of the object detection model. Here's a quick guide on how to interpret it:

*   **Rows (True Labels):** Each row corresponds to the actual class of the objects.
*   **Columns (Predicted Labels):** Each column corresponds to the class predicted by the model.
*   **Diagonal Cells:** These cells show the number of instances where the model correctly identified an object's class.
*   **Off-Diagonal Cells:** These cells indicate misclassifications, where the model predicted a different class than the actual one.

In addition to the visual matrix, we have also printed the Mean Average Precision (mAP) values:
*   **mAP50(B):** This metric represents the Mean Average Precision calculated at an Intersection over Union (IoU) threshold of 0.50. It's a widely used metric for object detection, indicating the model's ability to correctly detect and localize objects.
*   **mAP50-95(B):** This is a more comprehensive metric that averages the mAP over various IoU thresholds, ranging from 0.50 to 0.95. It provides a better understanding of the model's performance across different levels of detection accuracy.
"""

import os, glob
import yaml
from collections import Counter
import matplotlib.pyplot as plt

# Roboflow gives the dataset folder path here
dataset_dir = dataset.location
print("Dataset folder:", dataset_dir)

yaml_path = os.path.join(dataset_dir, "data.yaml")
with open(yaml_path, "r") as f:
    data = yaml.safe_load(f)

class_names = data.get("names", [])
nc = data.get("nc", len(class_names))

def count_split(split_name):
    img_dir = os.path.join(dataset_dir, split_name, "images")
    lbl_dir = os.path.join(dataset_dir, split_name, "labels")

    images = []
    for ext in ("*.jpg", "*.jpeg", "*.png", "*.bmp", "*.webp"):
        images += glob.glob(os.path.join(img_dir, ext))

    label_files = glob.glob(os.path.join(lbl_dir, "*.txt"))

    counter = Counter()
    total_instances = 0

    for lf in label_files:
        with open(lf, "r") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                cls_id = int(line.split()[0])
                counter[cls_id] += 1
                total_instances += 1

    return len(images), len(label_files), total_instances, counter

splits = ["train", "valid", "test"]
split_summary = {}
global_counter = Counter()
global_instances = 0

for sp in splits:
    img_n, lbl_n, inst_n, c = count_split(sp)
    split_summary[sp] = (img_n, lbl_n, inst_n)
    global_counter.update(c)
    global_instances += inst_n

# -------- Print dataset split table --------
print("\n=== Dataset Split Summary ===")
print(f"{'Subset':<10}{'#Images':>10}{'#Labels':>10}{'#Instances':>14}")
for sp in splits:
    img_n, lbl_n, inst_n = split_summary[sp]
    print(f"{sp:<10}{img_n:>10}{lbl_n:>10}{inst_n:>14}")
print(f"{'TOTAL':<10}{sum(split_summary[s][0] for s in splits):>10}{sum(split_summary[s][1] for s in splits):>10}{global_instances:>14}")

if global_instances == 0:
    raise ValueError("No instances found in labels. Check dataset paths or label files.")

# -------- Class distribution --------
labels = []
counts = []
print("\n=== Class Distribution (Instances) ===")
print(f"{'Class':<20}{'Instances':>12}{'Percent':>12}")
for cls_id in range(nc):
    name = class_names[cls_id] if cls_id < len(class_names) else f"class_{cls_id}"
    inst = global_counter.get(cls_id, 0)
    pct = (inst / global_instances) * 100
    print(f"{name:<20}{inst:>12}{pct:>11.2f}%")
    labels.append(name)
    counts.append(inst)

# -------- Save pie chart --------
pie_path = os.path.join(dataset_dir, "class_distribution_pie.png")
plt.figure(figsize=(7, 5.5))
plt.pie(counts, labels=labels, autopct="%1.1f%%", startangle=140)
plt.title("Class Distribution (Before Balancing)")
plt.tight_layout()
plt.savefig(pie_path, dpi=200)
plt.close()

# -------- Save bar chart --------
bar_path = os.path.join(dataset_dir, "class_distribution_bar.png")
plt.figure(figsize=(7.5, 4.8))
plt.bar(labels, counts)
plt.xlabel("Class")
plt.ylabel("Instances")
plt.title("Instances per Class")
plt.xticks(rotation=20, ha="right")
plt.tight_layout()
plt.savefig(bar_path, dpi=200)
plt.close()

print("\n✅ Saved:")
print(" -", pie_path)
print(" -", bar_path)

from PIL import Image
import matplotlib.pyplot as plt

pie_path = "/content/Bird_UAV-1/class_distribution_pie.png"
bar_path = "/content/Bird_UAV-1/class_distribution_bar.png"

plt.figure(figsize=(7,5))
plt.imshow(Image.open(pie_path))
plt.axis("off")
plt.title("class_distribution_pie.png")
plt.show()

plt.figure(figsize=(7,5))
plt.imshow(Image.open(bar_path))
plt.axis("off")
plt.title("class_distribution_bar.png")
plt.show()

from google.colab import files
files.download("/content/Bird_UAV-1/class_distribution_pie.png")
files.download("/content/Bird_UAV-1/class_distribution_bar.png")